### ISSUE TITLE
TypeError: undefined is not a function at Object.<anonymous> 

### ISSUE THREAD

**Issue by ssteinerx** [timothyarmes/packagecheck#2]
Maybe I'm missing something obvious, but running `packagecheck` in the ./packages directory of a Meteor project, I get this:

```
(exports, require, module, __filename, __dirname) { var path = Npm.require('p
                                                                    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/ssteiner/Desktop/meteor/val-dashboard/packages/npm-container/package.js:1:78)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/packagecheck/index.js:55:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/packagecheck/index.js:49:9)
```

**Comment by timothyarmes** [comment]
Thanks. Fixed in 0.1.5.

**Comment by ssteinerx** [comment]
Thanks!  When will you push the package?

**Comment by timothyarmes** [comment]
I have. You may not see it on npmsj straight away, but you should still be able to install it..
