### ISSUE TITLE
Incompatible with Meteor 1.2?

### ISSUE THREAD

**Issue by SachaG** [timothyarmes/packagecheck#6]
Seems like the new `api.addAssets` is triggering an error?

```
/Users/sacha/Dev/Telescope/packages/telescope-core/package.js:76
  api.addAssets([
      ^
TypeError: Object #<Object> has no method 'addAssets'
    at /Users/sacha/Dev/Telescope/packages/telescope-core/package.js:76:7
    at Object.Package.onUse (/usr/local/lib/node_modules/packagecheck/package.js:102:5)
    at Object.<anonymous> (/Users/sacha/Dev/Telescope/packages/telescope-core/package.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/packagecheck/index.js:65:11
```

**Comment by timothyarmes** [comment]
Thanks. I've pushed a fix.
